<?php

namespace App\Http\Controllers\Dashboard\UserList;


use App\Exports\UserPhoneExport;
use App\Http\Controllers\Controller;
use App\Model\Area\District;
use App\Model\Area\Thana;
use App\Model\Area\Village;
use App\Model\Area\Zone;
use App\Model\Transaction\Transaction;
use App\Model\User\UserVerification;
use App\Model\User\UserVerificationDetail;
use App\User;
use App\UserJob;
use App\UserJobType;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use Kreait\Firebase\Storage;
use Maatwebsite\Excel\Facades\Excel;
use Yajra\DataTables\DataTables;

class UserListController extends Controller
{
    public function index()
    {
        /*$users = User::latest()->get();
        return view('dashboard.user-list.index', compact('users'));*/
        return view('dashboard.user-list.index');
    }


    public function bvonUserPhoneExcel(){
        return Excel::download(new UserPhoneExport, 'invoices.xlsx');
    }

    public function userActionBonus(Request $request){
        User::where('id', $request->id)->update(['action_active' => $request->value]);
        return $request->id;
    }





    public function userDatatables(Request $request)
    {
        DB::statement(DB::raw('set @rownum=0'));
        $users = User::select([
            DB::raw('@rownum  := @rownum  + 1 AS rownum'),
            'id',
            'name',
            'phone',
            'type',
            'referral_id',
            'dealer_referral_id',
            'dealer_referral_by',
            'action_active'
        ]);



        $datatables = Datatables::of($users)
            ->addColumn('action', function ($user) {
                if($user->action_active){
                    $checked = "checked";
                }else{
                    $checked ='sdfasda';
                }
                return ' <input type="text" name="quantity" class="dbaccount" data-id="'.$user->id.'" value="'.$user->dealer_referral_id.'" > &nbsp;<a href="'. route('bf.user.details', ['user' => $user->id]) .'" class="btn btn-alt-primary cu-popover" data-content="See Details" data-placement="top">
                                        <i class="si si-info"></i>
                                    </a> &nbsp; <input type="text" name="dbaccountby" class="dbaccountBy" data-id="'.$user->id.'" value="'.$user->dealer_referral_by.'" >  <input type="checkbox" name="actionActive" class="actionActive" data-id="'.$user->id.'" '.$checked.' value="1" >';

            });



        if ($keyword = $request->get('search')['value']) {
            $datatables->filterColumn('rownum', function($value) {});
        }

        return $datatables->make(true);
    }




    public function show(User $user)
    {
        return view('dashboard.user-list.details', compact('user'));
    }

    public function updateUserDetails(Request $request){
      if($request->isMethod('post'))  {
          $data = $request->all();
            User::where('id', $data['id'])->update(['name'=> $data['name'], 'phone' => $data['phone'], 'nick_name' => $data['nick_name'], 'gender'=> $data['gender'],'birthday'=> $data['birthday'], 'hometown' => $data['hometown'], 'lives_in' => $data['lives_in'], 'religion' => $data['religion'], 'occupation' => $data['occupation']]);
          return redirect()->back();
      }
    }




    public function assign_job()
    {
        $user_job_types = UserJobType::all();
        $premium_user = User::where('verified', 1)->where('referral_id', '!=', null)->where('type', '!=', 'GU')->get();
        $users = $premium_user->filter(function($user){
            return $user->job == null;
        });
        $zones = Zone::all();

        $business_developers = $premium_user->filter(function($user){
            return $user->has_job() && $user->job->job_type->name === "B-Developer";
        });


        return view('dashboard.user-list.assign_job', compact('user_job_types', 'users', 'zones', 'business_developers'));
    }
    public function assign_job_store(Request $request)
    {

        if($request->query('assign_job') === 'B-Developer') {
            if(User::find($request->user_id)->has_job()) return back()->with(["error" => "already assigned a job to this user"]);
            $success = UserJob::create([
                "user_id" => $request->user_id,
                "user_job_type_id" => $request->job_type,
                "area_type" => null,
                "area_id" => null,
            ]);
        } else if($request->query('assign_job') === 'Divisional Manager') {
            $success = Zone::find($request->area)->area()->create([
                "user_id" => $request->user_id,
                "user_job_type_id" => $request->job_type,
            ]);
        } else if($request->query('assign_job') === 'District Manager') {
            $success = District::find($request->area)->area()->create([
                "user_id" => $request->user_id,
                "user_job_type_id" => $request->job_type,
            ]);
        } else if($request->query('assign_job') === 'Area Manager') {
            $success = Thana::find($request->area)->area()->create([
                "user_id" => $request->user_id,
                "user_job_type_id" => $request->job_type,
            ]);
        } else if($request->query('assign_job') === 'Brand Promoter') {
            $success = Village::find($request->area)->area()->create([
                "user_id" => $request->user_id,
                "user_job_type_id" => $request->job_type,
            ]);
        }

        if($success) return back()->with(["success" => "Job has been assigned successfully"]);

    }

    public function job_list()
    {
        $job_list = UserJob::orderBy('user_job_type_id', 'asc');

        if($area_id = request()->query('village_id')) {
            $area = Village::findOrFail($area_id);
            $job_list = $area->area();
        } else if($area_id = request()->query('thana_id')) {
            $area = Thana::findOrFail($area_id);
            $job_list = $area->area();
        } else if($area_id = request()->query('district_id')) {
            $area = District::findOrFail($area_id);
            $job_list = $area->area();
        } else if($area_id = request()->query('zone_id')) {
            $area = Zone::findOrFail($area_id);
            $job_list = $area->area();
        }

        if($job_type_id = request()->query('user_job_type_id')) {
            $job_list = $job_list->where('user_job_type_id', $job_type_id);
        }



        $job_list = $job_list->orderBy('user_job_type_id', 'asc')->get();




        $zones = Zone::all();
        $job_types = UserJobType::all();
        return view('dashboard.user-list.job_list', compact('job_list', 'zones', 'job_types'));
    }

    public function changePassword(User $user, Request $request)
    {
        $request->validate([
            'password' => 'required|confirmed|min:6'
        ]);
        $updated = $user->update([
            "password" => bcrypt($request->password)
        ]);

        if($updated) return back()->with(["success" => "Password has been change successfully"]);
    }


    public function addOrMinusBalance(Request $request){

        if ($request->isMethod('post')){
            $data = $request->all();
            if(empty($data['mesage'])){
                $data['mesage'] = '';
            }
            if(!empty($data['balance_add'])){
                $transaction = new Transaction();
                $transaction->user_id = $data['user_id'];
                $transaction->category = 'admin_user_balance';
                $transaction->amount_type = "c";
                $transaction->amount = $data['balance'];
                $transaction->message = $data['message'];
                $transaction->data = '';
                $transaction->check_date = date('Y-m-d');
                $transaction->save();
                return redirect()->back();
            }else{
                $transaction = new Transaction();
                $transaction->user_id = $data['user_id'];
                $transaction->category = 'admin_user_balance';
                $transaction->amount_type = "d";
                $transaction->amount = $data['balance'];
                $transaction->message = $data['message'];
                $transaction->data = '';
                $transaction->check_date = date('Y-m-d');
                $transaction->save();
                return redirect()->back();

            }

        }
    }





    public function treeView()
    {
        $users = User::paginate(10);

        return view('dashboard.user-list.tree-view', compact('users'));
    }

    public function create()
    {
        $premium_users = User::whereNotNull('referral_id')->get();
        return view('dashboard.user-list.create', compact('premium_users'));
    }

    public function store(Request $request)
    {
        $request->validate([
           "name" => "required|min:3",
           "phone" => "required|unique:users|min:10",
           "password" => "required|confirmed",
           "password_confirmation" => "required",
           "device_id" => "required",
           "referred_by" => "required",
        ]);

        $user = User::create([
            "name" => $request->name,
            "uuid" => Str::uuid(),
            "fuuid" => Str::uuid(),
            "phone" => $request->phone,
            "password" => Hash::make($request->password),
            "device_id" => $request->device_id,
            "referred_by" => $request->referred_by,
        ]);

        $profile_pic = "/9j/4AAQSkZJRgABAQEAYABgAAD/4RCQRXhpZgAATU0AKgAAAAgABQESAAMAAAABAAEAAAE7AAIAAAAGAAAIVodpAAQAAAABAAAIXJydAAEAAAAMAAAQfOocAAcAAAgMAAAASgAAAAAc6gAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEhBU0FOAAAB6hwABwAACAwAAAhuAAAAABzqAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABIAEEAUwBBAE4AAAD/4QpeaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wLwA8P3hwYWNrZXQgYmVnaW49J++7vycgaWQ9J1c1TTBNcENlaGlIenJlU3pOVGN6a2M5ZCc/Pg0KPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyI+PHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj48cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0idXVpZDpmYWY1YmRkNS1iYTNkLTExZGEtYWQzMS1kMzNkNzUxODJmMWIiIHhtbG5zOmRjPSJodHRwOi8vcHVybC5vcmcvZGMvZWxlbWVudHMvMS4xLyIvPjxyZGY6RGVzY3JpcHRpb24gcmRmOmFib3V0PSJ1dWlkOmZhZjViZGQ1LWJhM2QtMTFkYS1hZDMxLWQzM2Q3NTE4MmYxYiIgeG1sbnM6ZGM9Imh0dHA6Ly9wdXJsLm9yZy9kYy9lbGVtZW50cy8xLjEvIj48ZGM6Y3JlYXRvcj48cmRmOlNlcSB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPjxyZGY6bGk+SEFTQU48L3JkZjpsaT48L3JkZjpTZXE+DQoJCQk8L2RjOmNyZWF0b3I+PC9yZGY6RGVzY3JpcHRpb24+PC9yZGY6UkRGPjwveDp4bXBtZXRhPg0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8P3hwYWNrZXQgZW5kPSd3Jz8+/9sAQwACAQECAQECAgICAgICAgMFAwMDAwMGBAQDBQcGBwcHBgcHCAkLCQgICggHBwoNCgoLDAwMDAcJDg8NDA4LDAwM/9sAQwECAgIDAwMGAwMGDAgHCAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwM/8AAEQgAZABkAwEiAAIRAQMRAf/EAB8AAAEFAQEBAQEBAAAAAAAAAAABAgMEBQYHCAkKC//EALUQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQygZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5+v/EAB8BAAMBAQEBAQEBAQEAAAAAAAABAgMEBQYHCAkKC//EALURAAIBAgQEAwQHBQQEAAECdwABAgMRBAUhMQYSQVEHYXETIjKBCBRCkaGxwQkjM1LwFWJy0QoWJDThJfEXGBkaJicoKSo1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoKDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uLj5OXm5+jp6vLz9PX29/j5+v/aAAwDAQACEQMRAD8A+0KKKK/YD8nCg9KKCcCgBpOP89K0vDPgzWPGe7+x9J1LVApKlrW2eVQR1BKgjP417Z+yZ+y5aeOdPj8UeJYPP01mP9n2JOFudpIMsncruGFXjO0k5BGfqqzsobG1jhgjjhhhUJHHGu1UUcAADgAelfNZjxFGhN0qMeZrdt6XPosv4flWpqrVlyp7Lqfn/dfA/wAZ2ULSTeFPECxqMlvsTtj8hXLyI1vcyQSLJFNC22SN1KuhxnBU8g+x9a/SwqBXI/Fn4KeH/jFpJttYtN1wi4gvIvluLfuNrdxn+E5U9xXFh+KpOVq0NPL/AIO/3o7K3DKUb0Z6+f8AwP8AgnwGvSitn4jeAL/4W+NL7Q9Sw1xZsNsyrtS4jYZSRRk4DDtk4ORkkGsUHmvsKc4zipwd09T5OpTlCTjLdC0UUVRIUUUUAFFFFAATiiCym1S5jtYPlnupFgiz/fchV/Uig1a8NXqab4n0u6kOI7e9gmc+irKrH9BUzuotrexVNJySex+imgaDb+GtGs9Ps4/LtbGFLeFc/dRVCgfkKvAYFGaK/IXq7s/VlorIOtA4oooA+Zf+Cg/hZFTwzriALLvl0+b1kUgSR/8AfJWT/vv2FfNi19U/8FB7xYvAXh63/im1NnHrhYmz/MfnXystfovDsm8DG/Rv8z8/z6KWMlby/IWiiivbPHCiiigAooooAKjuYBcQSRt92RSp+hGKexpPx/WgD9CPhH4yX4g/DXRNaV1ke/tEeUjtKBtkH4OGFdKp4r5e/YW+MkWmyz+DNQm8v7RI1zpRY/KzHLSw+xON49SX74z9Po+RX5bmWDeGxMqb26ej2P0vL8UsRQjUW/X1W4+im5IFZPjfxvYfDzwveazqk3kWNim+RgNzMScBVHdmYgAdya4oxcpcsdWdcpKKvLRHzD+354qXVPiHoukRsD/Y9k80gHZ52Xg/RYgR/vGvCBwa0/HPi+6+IPjHUtcvlVbrVJzOyA7hGMBVQHvtVVXPcKKzB1r9Ty/DfV8NCk90tfXqfmuOxHt8ROqtm/wWwtFFFdhxhRRRQAUmaWm5waADO5lAyzMdoUDJJPQAdz7V6r4C/Y28a+NljmubaHw/aPgiS+b96R6iJcsO/D7T/Ou3/YP+Edvq1zfeLr6FZms5fsmmhv8Alm+3Msv1w6qD2+f14+n/AC6+TzfiCdGq6FBK63f+XofUZVkcK1NVq97PZf5ny78Qf2DLrQvB9tdeG9UuNU1yzJe4im224ujkFTCQR5TLjgMxz/eBGTS8F/tu+JPh7L/Y/jDRpNRurXCvJI32O+Qeroy7XPTn5Omctmvq7Gapa74X0zxVbrDqenWOoQryqXMCyqv0DA4/CvEjnHtI8mNh7RdHs181+R7Esp9nLnwcuR9Vun8meBat/wAFDdLhsmaz8MalNNjhbm7jhj/Fl3n9DXCJYfED9tPX7aa426f4et3JScRFbG17FkBO6eTjHBOOmUBr6gsfgx4R0ufzLfwxoMMgO4MLGPIPtxXTslUsyw9D3sJStLvJ3t6LYTy/EVtMVUvHtFWv6s+Y/iB/wT+mhJm8L60si7QPsmpLgk45ImQd/Qp369BXh3j74XeIfhZeLDr2l3Gn+cxWKUlZIZiOflkUlScc4zu9QK/Q0rkYrJ8aeDdP8e+G7zR9UhW4sb5NkidCO4YHsykAg9iK3wfEeIptKt7y69/69TDF8P4eabo+6/wPzq3c0taHjDwtceBvFmpaLdtvudLuGt3cLt8zB4bHbcMN9GFZ9feRmpxUo7M+JlFxbjLdBRRRVEhTT/8AXp1Q3xYWk2wbm2naPU9qPMEfef7Lvhz/AIRb4C+GbYgh5bT7W+eu6Z2mP6v+WK7+qeiaVHoWk2djD/qbOBIE/wB1VCj9AKuV+R1qjnUlN9W2fqlGnyU4w7JIKKKKzNAooooAKa/NOppHNJgfGf7b/h1dG+Ocl2qgf2xYwXDf7TpmIn/vlEH4V5DX0d/wUN0vbe+EL5VHK3dvI3dv9Sy/l8/51841+m5LU58FTb7W+52PzrOKfJjJrzv96uFFFFeoeYFOtp1tbuGV1Zo45FdlXqwDAkD8v1ptNPWi19ATs7n6NeFPGmleOdJjvtHvrfULSQAiSF9232YdVPsQCPStPdX5s6RqV14f1BbzT7q5sbtRgTW0rRSY9MqQcf4V6L4X/bA+IHhgKjatHq0K4AS/t0kK/wDA1CufqzGviK/C1ZO9CSa89D7KhxLSatWi0/LVH3FuoDZr5a0X/goZqMIVdS8K2dxz80lrftDgf7jI2f8AvoV1Onf8FA/DM6/6RouvW/f5RFJ/JxXmVMjx0N6bfpZ/kz0oZzg5fbXzuj3wnFAORXhs37fPg9Vylh4hdsdPs0a/+1Kw9X/4KHafFGf7O8LahcN2+03iQKfxVZD+lZxyfGydlTfz0/MqWb4OKu6i/P8AI+jWcKKRjmvkPxD+3v4u1RWGn6doulq33SVe5dfxJUH/AL5rzfxf8bvF3j2Fo9W8RaldQuMNCjLbwsPQpGFU/iDXoUeGcVL+I1H8X+H+Zw1uIsNFfu05fh+f+R7R+3x450nWLbQ9GtL63utSsrqSe5jhcP8AZ12bMORwGLHoeflNfONRxxLCFVVCqOgHQVJX2WX4NYWgqMXe36nyeOxbxNZ1mrXCiiiuw4woxmiigAxRiiigBNopaKKACjFFFABijFFFABiiiigAooooA//Z";
        $cover_pic = "/9j/4AAQSkZJRgABAQEASABIAAD//gAnMTgxMzM1MWEtMDY3NS00MTg5LWE4MGQtZTA1NDZmN2FkYzIzAP/tDYhQaG90b3Nob3AgMy4wADhCSU0EBAAAAAAABxwCAAACAAAAOEJJTQQlAAAAAAAQ6PFc8y/BGKGie2etxWTVujhCSU0EOgAAAAAA5QAAABAAAAABAAAAAAALcHJpbnRPdXRwdXQAAAAFAAAAAFBzdFNib29sAQAAAABJbnRlZW51bQAAAABJbnRlAAAAAENscm0AAAAPcHJpbnRTaXh0ZWVuQml0Ym9vbAAAAAALcHJpbnRlck5hbWVURVhUAAAAAQAAAAAAD3ByaW50UHJvb2ZTZXR1cE9iamMAAAAMAFAAcgBvAG8AZgAgAFMAZQB0AHUAcAAAAAAACnByb29mU2V0dXAAAAABAAAAAEJsdG5lbnVtAAAADGJ1aWx0aW5Qcm9vZgAAAAlwcm9vZkNNWUsAOEJJTQQ7AAAAAAItAAAAEAAAAAEAAAAAABJwcmludE91dHB1dE9wdGlvbnMAAAAXAAAAAENwdG5ib29sAAAAAABDbGJyYm9vbAAAAAAAUmdzTWJvb2wAAAAAAENybkNib29sAAAAAABDbnRDYm9vbAAAAAAATGJsc2Jvb2wAAAAAAE5ndHZib29sAAAAAABFbWxEYm9vbAAAAAAASW50cmJvb2wAAAAAAEJja2dPYmpjAAAAAQAAAAAAAFJHQkMAAAADAAAAAFJkICBkb3ViQG/gAAAAAAAAAAAAR3JuIGRvdWJAb+AAAAAAAAAAAABCbCAgZG91YkBv4AAAAAAAAAAAAEJyZFRVbnRGI1JsdAAAAAAAAAAAAAAAAEJsZCBVbnRGI1JsdAAAAAAAAAAAAAAAAFJzbHRVbnRGI1B4bEBSAAAAAAAAAAAACnZlY3RvckRhdGFib29sAQAAAABQZ1BzZW51bQAAAABQZ1BzAAAAAFBnUEMAAAAATGVmdFVudEYjUmx0AAAAAAAAAAAAAAAAVG9wIFVudEYjUmx0AAAAAAAAAAAAAAAAU2NsIFVudEYjUHJjQFkAAAAAAAAAAAAQY3JvcFdoZW5QcmludGluZ2Jvb2wAAAAADmNyb3BSZWN0Qm90dG9tbG9uZwAAAAAAAAAMY3JvcFJlY3RMZWZ0bG9uZwAAAAAAAAANY3JvcFJlY3RSaWdodGxvbmcAAAAAAAAAC2Nyb3BSZWN0VG9wbG9uZwAAAAAAOEJJTQPtAAAAAAAQAEgAAAABAAEASAAAAAEAAThCSU0EJgAAAAAADgAAAAAAAAAAAAA/gAAAOEJJTQQNAAAAAAAEAAAAHjhCSU0EGQAAAAAABAAAAB44QklNA/MAAAAAAAkAAAAAAAAAAAEAOEJJTScQAAAAAAAKAAEAAAAAAAAAAThCSU0D9QAAAAAASAAvZmYAAQBsZmYABgAAAAAAAQAvZmYAAQChmZoABgAAAAAAAQAyAAAAAQBaAAAABgAAAAAAAQA1AAAAAQAtAAAABgAAAAAAAThCSU0D+AAAAAAAcAAA/////////////////////////////wPoAAAAAP////////////////////////////8D6AAAAAD/////////////////////////////A+gAAAAA/////////////////////////////wPoAAA4QklNBAgAAAAAABAAAAABAAACQAAAAkAAAAAAOEJJTQQeAAAAAAAEAAAAADhCSU0EGgAAAAADeQAAAAYAAAAAAAAAAAAAA4QAAAZAAAAAIgBzAGkAbABpAGMAbwBuAC0AdgBhAGwAbABlAHkALQBoAGIAbwAtAGIAYQBjAGsAZwByAG8AdQBuAGQALQAxADkAMgAwAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAZAAAADhAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAABAAAAABAAAAAAAAbnVsbAAAAAIAAAAGYm91bmRzT2JqYwAAAAEAAAAAAABSY3QxAAAABAAAAABUb3AgbG9uZwAAAAAAAAAATGVmdGxvbmcAAAAAAAAAAEJ0b21sb25nAAADhAAAAABSZ2h0bG9uZwAABkAAAAAGc2xpY2VzVmxMcwAAAAFPYmpjAAAAAQAAAAAABXNsaWNlAAAAEgAAAAdzbGljZUlEbG9uZwAAAAAAAAAHZ3JvdXBJRGxvbmcAAAAAAAAABm9yaWdpbmVudW0AAAAMRVNsaWNlT3JpZ2luAAAADWF1dG9HZW5lcmF0ZWQAAAAAVHlwZWVudW0AAAAKRVNsaWNlVHlwZQAAAABJbWcgAAAABmJvdW5kc09iamMAAAABAAAAAAAAUmN0MQAAAAQAAAAAVG9wIGxvbmcAAAAAAAAAAExlZnRsb25nAAAAAAAAAABCdG9tbG9uZwAAA4QAAAAAUmdodGxvbmcAAAZAAAAAA3VybFRFWFQAAAABAAAAAAAAbnVsbFRFWFQAAAABAAAAAAAATXNnZVRFWFQAAAABAAAAAAAGYWx0VGFnVEVYVAAAAAEAAAAAAA5jZWxsVGV4dElzSFRNTGJvb2wBAAAACGNlbGxUZXh0VEVYVAAAAAEAAAAAAAlob3J6QWxpZ25lbnVtAAAAD0VTbGljZUhvcnpBbGlnbgAAAAdkZWZhdWx0AAAACXZlcnRBbGlnbmVudW0AAAAPRVNsaWNlVmVydEFsaWduAAAAB2RlZmF1bHQAAAALYmdDb2xvclR5cGVlbnVtAAAAEUVTbGljZUJHQ29sb3JUeXBlAAAAAE5vbmUAAAAJdG9wT3V0c2V0bG9uZwAAAAAAAAAKbGVmdE91dHNldGxvbmcAAAAAAAAADGJvdHRvbU91dHNldGxvbmcAAAAAAAAAC3JpZ2h0T3V0c2V0bG9uZwAAAAAAOEJJTQQoAAAAAAAMAAAAAj/wAAAAAAAAOEJJTQQUAAAAAAAEAAAAAThCSU0EDAAAAAAEbAAAAAEAAACgAAAAWgAAAeAAAKjAAAAEUAAYAAH/2P/tAAxBZG9iZV9DTQAB/+4ADkFkb2JlAGSAAAAAAf/bAIQADAgICAkIDAkJDBELCgsRFQ8MDA8VGBMTFRMTGBEMDAwMDAwRDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAENCwsNDg0QDg4QFA4ODhQUDg4ODhQRDAwMDAwREQwMDAwMDBEMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwM/8AAEQgAWgCgAwEiAAIRAQMRAf/dAAQACv/EAT8AAAEFAQEBAQEBAAAAAAAAAAMAAQIEBQYHCAkKCwEAAQUBAQEBAQEAAAAAAAAAAQACAwQFBgcICQoLEAABBAEDAgQCBQcGCAUDDDMBAAIRAwQhEjEFQVFhEyJxgTIGFJGhsUIjJBVSwWIzNHKC0UMHJZJT8OHxY3M1FqKygyZEk1RkRcKjdDYX0lXiZfKzhMPTdePzRieUpIW0lcTU5PSltcXV5fVWZnaGlqa2xtbm9jdHV2d3h5ent8fX5/cRAAICAQIEBAMEBQYHBwYFNQEAAhEDITESBEFRYXEiEwUygZEUobFCI8FS0fAzJGLhcoKSQ1MVY3M08SUGFqKygwcmNcLSRJNUoxdkRVU2dGXi8rOEw9N14/NGlKSFtJXE1OT0pbXF1eX1VmZ2hpamtsbW5vYnN0dXZ3eHl6e3x//aAAwDAQACEQMRAD8A1WhEaFFoRGhFDIBTAUWhEaEVLgKYCQCmAkpQCkGpwFIBJTHakW6IgCW0nQalJSPamLUXamISUiIUCEYhQISUhIUCEYhDISUhcFAhFcFBwQUhIUCEVwQ3BJT/AP/Q2GojQoNRGooZtCI0KDURqKmbQpgKLURqSlwFMBMApgJIUAs36y4mZm9AzsLBE5eVWK6huDJG5r7ve7837Oy3d+//ADa1AEnB4IfXG5siHTBDh7hLfouSUioZY2isWVegdrYqO2Wt2tDR+iLq2/2FIhFcdxBgNAAAaDMR5qBCSkRCgQikKBSSiIQ3BFchuSUicENyK5DckpE5DciuQ3IKf//R2WojUNqI1FCRqI1DaiNRUkaiNQ2ojUlJAphQCmEkMgpQohPKSlFRKkSoFJTEoblMqBSSwchuU3IbklI3IbkRyG5JSNyG5EchuQU//9LYaiNQmojUUJmojUFpRGlFSVqI0oTSpgpKSgqYKECpgpKSAp5UJSlJDMlRJTSokpKUSoEpyVAlJLFxUHKRKG4pKYuQ3KTioOSUwchuU3IbkFP/09ZpRGlCaVMFFCYFTaUJpUwUVJgVMFBBUwUlJgVIFCBTgpKS7k8oe5LckpJuUSVHcmLklLkqJKYlRJSUolDcU5KgSkpZxQyVIlDJQUxcVBxUiUMlJT//1NMFTBQgiBFCQFTBQwpBJSUFTBQgphFSQOUg5DCcJKSbktygnSUy3Ji5RSSUuXKJKYqJSUolQJTlQKSliVAlOVAoKWJQyVIqBSU//9k4QklNBCEAAAAAAFcAAAABAQAAAA8AQQBkAG8AYgBlACAAUABoAG8AdABvAHMAaABvAHAAAAAUAEEAZABvAGIAZQAgAFAAaABvAHQAbwBzAGgAbwBwACAAMgAwADIAMAAAAAEAOEJJTQQGAAAAAAAHAAEBAQABAQD/4QbORXhpZgAATU0AKgAAAAgADAEAAAMAAAABB4AAAAEBAAMAAAABBDgAAAECAAMAAAADAAAAngEGAAMAAAABAAIAAAESAAMAAAABAAEAAAEVAAMAAAABAAMAAAEaAAUAAAABAAAApAEbAAUAAAABAAAArAEoAAMAAAABAAIAAAExAAIAAAAhAAAAtAEyAAIAAAAUAAAA1odpAAQAAAABAAAA6gAAASIACAAIAAgAAABIAAAAAQAAAEgAAAABQWRvYmUgUGhvdG9zaG9wIDIxLjEgKE1hY2ludG9zaCkAADIwMjA6MDQ6MDcgMTg6MjI6NDEAAASQAAAHAAAABDAyMzGgAQADAAAAAQABAACgAgAEAAAAAQAABkCgAwAEAAAAAQAAA4QAAAAAAAAABgEDAAMAAAABAAYAAAEaAAUAAAABAAABcAEbAAUAAAABAAABeAEoAAMAAAABAAIAAAIBAAQAAAABAAABgAICAAQAAAABAAAFRQAAAAAAAABIAAAAAQAAAEgAAAAB/9j/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCABgAKADASEAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDfUcVKoqiSVRUqigCVRUqimBIBTwKAHBTS7aAEK03FADWFRkUARsKiYUARMKiYcUgIWFRGgCVRxUy0ASqOKmUUASqKlUUwJAKeBQA7FLigAxTSKAGEVGwoAjYcVCRQBEwqJhSAhaoWoAmUVMtAEq1MopgTKKlUUASAU8CgB4WmXE0VrbS3EzhIokLux/hUDJNACoyTRrJGwZGGQR3oIoAYwqMigCJhUTCgCFxULCkBC9RNQBKtTIKAJlFTJTAlUVMooAlFPUUAPxXO+PLSe98FajBbRmSUhGCggEhZFY9fQAn8KT2Bbmvpkhm0u2lKuu9A2HTawB5GR2OKtEUIGRkVEwpgROKhagCJ6gbpSAieoX6UASrUyUATLUydKYEy1MgoAkUVKBQA8CkZkjkR5AuzkDcuRuI4z+o/EUAiWbJkA3BgFAz/AJ/CoTSBkbComFMCJqhbpQBC1Qt0pAQtULUASp0qZOlAEydKmXpTAmXoKmXpQBKtSKKAJAKUgEYIyDQITAAAAwAMADtTWoAiaom6UDIm61CwoAhaoG6GkBC1Qt0NAEqdKmTpQBMvb6VMvSmBOtSr0FAEy9KlWgB4p/agQ01G3SgCNulRGgZC3WomoAgbrUL9DSAhaoG6GgCVOlTJ0oAmXt9KmXpTAmXtUy9BQBKvSpVoAkFOzQIaaY1AEbVCaBkTdaiagCBqgbvSAiaoG6GgCRamTpQBOnSpl6UwJl6VKtAEq1KDQBIDS5oEITUZNAEbVGx4oGQtULdKAIWqFulICFqhbpQBItSpQBOpqZDTAlU1MpoAlBqQGgBwNO3fSgQhNNJoAjY1Ex4oGRMahY8UAQtULUgIWqFjxQA9f51MpoAmWplNMCYGpVNAEqmnqaAHg0uaBCE00mgCMmo2NAyJzUTGgCFzULUgIXNQtQA8VMpoAmBqVTQBKp4qVTTAkBqQGgB2aXdQAEmmk0AMY1GTQBExqJjQBCxqFjzSAiY1CxoA/9kA/+IMWElDQ19QUk9GSUxFAAEBAAAMSExpbm8CEAAAbW50clJHQiBYWVogB84AAgAJAAYAMQAAYWNzcE1TRlQAAAAASUVDIHNSR0IAAAAAAAAAAAAAAAEAAPbWAAEAAAAA0y1IUCAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARY3BydAAAAVAAAAAzZGVzYwAAAYQAAABsd3RwdAAAAfAAAAAUYmtwdAAAAgQAAAAUclhZWgAAAhgAAAAUZ1hZWgAAAiwAAAAUYlhZWgAAAkAAAAAUZG1uZAAAAlQAAABwZG1kZAAAAsQAAACIdnVlZAAAA0wAAACGdmlldwAAA9QAAAAkbHVtaQAAA/gAAAAUbWVhcwAABAwAAAAkdGVjaAAABDAAAAAMclRSQwAABDwAAAgMZ1RSQwAABDwAAAgMYlRSQwAABDwAAAgMdGV4dAAAAABDb3B5cmlnaHQgKGMpIDE5OTggSGV3bGV0dC1QYWNrYXJkIENvbXBhbnkAAGRlc2MAAAAAAAAAEnNSR0IgSUVDNjE5NjYtMi4xAAAAAAAAAAAAAAASc1JHQiBJRUM2MTk2Ni0yLjEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFhZWiAAAAAAAADzUQABAAAAARbMWFlaIAAAAAAAAAAAAAAAAAAAAABYWVogAAAAAAAAb6IAADj1AAADkFhZWiAAAAAAAABimQAAt4UAABjaWFlaIAAAAAAAACSgAAAPhAAAts9kZXNjAAAAAAAAABZJRUMgaHR0cDovL3d3dy5pZWMuY2gAAAAAAAAAAAAAABZJRUMgaHR0cDovL3d3dy5pZWMuY2gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZGVzYwAAAAAAAAAuSUVDIDYxOTY2LTIuMSBEZWZhdWx0IFJHQiBjb2xvdXIgc3BhY2UgLSBzUkdCAAAAAAAAAAAAAAAuSUVDIDYxOTY2LTIuMSBEZWZhdWx0IFJHQiBjb2xvdXIgc3BhY2UgLSBzUkdCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGRlc2MAAAAAAAAALFJlZmVyZW5jZSBWaWV3aW5nIENvbmRpdGlvbiBpbiBJRUM2MTk2Ni0yLjEAAAAAAAAAAAAAACxSZWZlcmVuY2UgVmlld2luZyBDb25kaXRpb24gaW4gSUVDNjE5NjYtMi4xAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB2aWV3AAAAAAATpP4AFF8uABDPFAAD7cwABBMLAANcngAAAAFYWVogAAAAAABMCVYAUAAAAFcf521lYXMAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAKPAAAAAnNpZyAAAAAAQ1JUIGN1cnYAAAAAAAAEAAAAAAUACgAPABQAGQAeACMAKAAtADIANwA7AEAARQBKAE8AVABZAF4AYwBoAG0AcgB3AHwAgQCGAIsAkACVAJoAnwCkAKkArgCyALcAvADBAMYAywDQANUA2wDgAOUA6wDwAPYA+wEBAQcBDQETARkBHwElASsBMgE4AT4BRQFMAVIBWQFgAWcBbgF1AXwBgwGLAZIBmgGhAakBsQG5AcEByQHRAdkB4QHpAfIB+gIDAgwCFAIdAiYCLwI4AkECSwJUAl0CZwJxAnoChAKOApgCogKsArYCwQLLAtUC4ALrAvUDAAMLAxYDIQMtAzgDQwNPA1oDZgNyA34DigOWA6IDrgO6A8cD0wPgA+wD+QQGBBMEIAQtBDsESARVBGMEcQR+BIwEmgSoBLYExATTBOEE8AT+BQ0FHAUrBToFSQVYBWcFdwWGBZYFpgW1BcUF1QXlBfYGBgYWBicGNwZIBlkGagZ7BowGnQavBsAG0QbjBvUHBwcZBysHPQdPB2EHdAeGB5kHrAe/B9IH5Qf4CAsIHwgyCEYIWghuCIIIlgiqCL4I0gjnCPsJEAklCToJTwlkCXkJjwmkCboJzwnlCfsKEQonCj0KVApqCoEKmAquCsUK3ArzCwsLIgs5C1ELaQuAC5gLsAvIC+EL+QwSDCoMQwxcDHUMjgynDMAM2QzzDQ0NJg1ADVoNdA2ODakNww3eDfgOEw4uDkkOZA5/DpsOtg7SDu4PCQ8lD0EPXg96D5YPsw/PD+wQCRAmEEMQYRB+EJsQuRDXEPURExExEU8RbRGMEaoRyRHoEgcSJhJFEmQShBKjEsMS4xMDEyMTQxNjE4MTpBPFE+UUBhQnFEkUahSLFK0UzhTwFRIVNBVWFXgVmxW9FeAWAxYmFkkWbBaPFrIW1hb6Fx0XQRdlF4kXrhfSF/cYGxhAGGUYihivGNUY+hkgGUUZaxmRGbcZ3RoEGioaURp3Gp4axRrsGxQbOxtjG4obshvaHAIcKhxSHHscoxzMHPUdHh1HHXAdmR3DHeweFh5AHmoelB6+HukfEx8+H2kflB+/H+ogFSBBIGwgmCDEIPAhHCFIIXUhoSHOIfsiJyJVIoIiryLdIwojOCNmI5QjwiPwJB8kTSR8JKsk2iUJJTglaCWXJccl9yYnJlcmhya3JugnGCdJJ3onqyfcKA0oPyhxKKIo1CkGKTgpaymdKdAqAio1KmgqmyrPKwIrNitpK50r0SwFLDksbiyiLNctDC1BLXYtqy3hLhYuTC6CLrcu7i8kL1ovkS/HL/4wNTBsMKQw2zESMUoxgjG6MfIyKjJjMpsy1DMNM0YzfzO4M/E0KzRlNJ402DUTNU01hzXCNf02NzZyNq426TckN2A3nDfXOBQ4UDiMOMg5BTlCOX85vDn5OjY6dDqyOu87LTtrO6o76DwnPGU8pDzjPSI9YT2hPeA+ID5gPqA+4D8hP2E/oj/iQCNAZECmQOdBKUFqQaxB7kIwQnJCtUL3QzpDfUPARANER0SKRM5FEkVVRZpF3kYiRmdGq0bwRzVHe0fASAVIS0iRSNdJHUljSalJ8Eo3Sn1KxEsMS1NLmkviTCpMcky6TQJNSk2TTdxOJU5uTrdPAE9JT5NP3VAnUHFQu1EGUVBRm1HmUjFSfFLHUxNTX1OqU/ZUQlSPVNtVKFV1VcJWD1ZcVqlW91dEV5JX4FgvWH1Yy1kaWWlZuFoHWlZaplr1W0VblVvlXDVchlzWXSddeF3JXhpebF69Xw9fYV+zYAVgV2CqYPxhT2GiYfViSWKcYvBjQ2OXY+tkQGSUZOllPWWSZedmPWaSZuhnPWeTZ+loP2iWaOxpQ2maafFqSGqfavdrT2una/9sV2yvbQhtYG25bhJua27Ebx5veG/RcCtwhnDgcTpxlXHwcktypnMBc11zuHQUdHB0zHUodYV14XY+dpt2+HdWd7N4EXhueMx5KnmJeed6RnqlewR7Y3vCfCF8gXzhfUF9oX4BfmJ+wn8jf4R/5YBHgKiBCoFrgc2CMIKSgvSDV4O6hB2EgITjhUeFq4YOhnKG14c7h5+IBIhpiM6JM4mZif6KZIrKizCLlov8jGOMyo0xjZiN/45mjs6PNo+ekAaQbpDWkT+RqJIRknqS45NNk7aUIJSKlPSVX5XJljSWn5cKl3WX4JhMmLiZJJmQmfyaaJrVm0Kbr5wcnImc951kndKeQJ6unx2fi5/6oGmg2KFHobaiJqKWowajdqPmpFakx6U4pammGqaLpv2nbqfgqFKoxKk3qamqHKqPqwKrdavprFys0K1ErbiuLa6hrxavi7AAsHWw6rFgsdayS7LCszizrrQltJy1E7WKtgG2ebbwt2i34LhZuNG5SrnCuju6tbsuu6e8IbybvRW9j74KvoS+/796v/XAcMDswWfB48JfwtvDWMPUxFHEzsVLxcjGRsbDx0HHv8g9yLzJOsm5yjjKt8s2y7bMNcy1zTXNtc42zrbPN8+40DnQutE80b7SP9LB00TTxtRJ1MvVTtXR1lXW2Ndc1+DYZNjo2WzZ8dp22vvbgNwF3IrdEN2W3hzeot8p36/gNuC94UThzOJT4tvjY+Pr5HPk/OWE5g3mlucf56noMui86Ubp0Opb6uXrcOv77IbtEe2c7ijutO9A78zwWPDl8XLx//KM8xnzp/Q09ML1UPXe9m32+/eK+Bn4qPk4+cf6V/rn+3f8B/yY/Sn9uv5L/tz/bf///+EM6Wh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8APD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4NCjx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDYuMC1jMDAyIDc5LjE2NDM1MiwgMjAyMC8wMS8zMC0xNTo1MDozOCAgICAgICAgIj4NCgk8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPg0KCQk8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21tLyIgeG1sbnM6c3RFdnQ9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZUV2ZW50IyIgeG1sbnM6ZGM9Imh0dHA6Ly9wdXJsLm9yZy9kYy9lbGVtZW50cy8xLjEvIiB4bWxuczpwaG90b3Nob3A9Imh0dHA6Ly9ucy5hZG9iZS5jb20vcGhvdG9zaG9wLzEuMC8iIHhtbG5zOnhtcD0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wLyIgeG1wTU06RG9jdW1lbnRJRD0iMjQwQzcxQkMxMjE1RTBBRTMwNTYwNTU3QTI1RTEyOTgiIHhtcE1NOkluc3RhbmNlSUQ9InhtcC5paWQ6YzFkNjM2YjQtOGI4Yi00ZGJkLWEzMTEtMDc3YmMyZThhZWZhIiB4bXBNTTpPcmlnaW5hbERvY3VtZW50SUQ9IjI0MEM3MUJDMTIxNUUwQUUzMDU2MDU1N0EyNUUxMjk4IiBkYzpmb3JtYXQ9ImltYWdlL2pwZWciIHBob3Rvc2hvcDpDb2xvck1vZGU9IjMiIHBob3Rvc2hvcDpJQ0NQcm9maWxlPSJzUkdCIElFQzYxOTY2LTIuMSIgeG1wOkNyZWF0ZURhdGU9IjIwMjAtMDQtMDdUMTc6NDE6MjgtMDQ6MDAiIHhtcDpNb2RpZnlEYXRlPSIyMDIwLTA0LTA3VDE4OjIyOjQxLTA0OjAwIiB4bXA6TWV0YWRhdGFEYXRlPSIyMDIwLTA0LTA3VDE4OjIyOjQxLTA0OjAwIj4NCgkJCTx4bXBNTTpIaXN0b3J5Pg0KCQkJCTxyZGY6U2VxPg0KCQkJCQk8cmRmOmxpIHN0RXZ0OmFjdGlvbj0ic2F2ZWQiIHN0RXZ0Omluc3RhbmNlSUQ9InhtcC5paWQ6YzFkNjM2YjQtOGI4Yi00ZGJkLWEzMTEtMDc3YmMyZThhZWZhIiBzdEV2dDp3aGVuPSIyMDIwLTA0LTA3VDE4OjIyOjQxLTA0OjAwIiBzdEV2dDpzb2Z0d2FyZUFnZW50PSJBZG9iZSBQaG90b3Nob3AgMjEuMSAoTWFjaW50b3NoKSIgc3RFdnQ6Y2hhbmdlZD0iLyIvPg0KCQkJCTwvcmRmOlNlcT4NCgkJCTwveG1wTU06SGlzdG9yeT4NCgkJPC9yZGY6RGVzY3JpcHRpb24+DQoJPC9yZGY6UkRGPg0KPC94OnhtcG1ldGE+DQogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPD94cGFja2V0IGVuZD0ndyc/Pv/bAEMAAgEBAgEBAgICAgICAgIDBQMDAwMDBgQEAwUHBgcHBwYHBwgJCwkICAoIBwcKDQoKCwwMDAwHCQ4PDQwOCwwMDP/bAEMBAgICAwMDBgMDBgwIBwgMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDP/AABEIASwB9AMBIgACEQEDEQH/xAAfAAABBQEBAQEBAQAAAAAAAAAAAQIDBAUGBwgJCgv/xAC1EAACAQMDAgQDBQUEBAAAAX0BAgMABBEFEiExQQYTUWEHInEUMoGRoQgjQrHBFVLR8CQzYnKCCQoWFxgZGiUmJygpKjQ1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4eLj5OXm5+jp6vHy8/T19vf4+fr/xAAfAQADAQEBAQEBAQEBAAAAAAAAAQIDBAUGBwgJCgv/xAC1EQACAQIEBAMEBwUEBAABAncAAQIDEQQFITEGEkFRB2FxEyIygQgUQpGhscEJIzNS8BVictEKFiQ04SXxFxgZGiYnKCkqNTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqCg4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2dri4+Tl5ufo6ery8/T19vf4+fr/2gAMAwEAAhEDEQA/APcUXc4/OrMH+tZv736VDarlM/xZxVqNSiYPWug5xyjcfpU0fQ/Wo0X5R74zUhT5cL1oAmh4jJ96tRp5YxUUMe8hfapwN1ADo+V/GpV6qv4UyNefapo4v4j9R70ATQLhl9qsAZNNiGI1+lPiXAJPrx9KAHoN1Sou5h+dIFx0qeBD93HQ81oA+JNzbv7vSp0GTn0pCPl4/CnxJwOPrQA9F7+1PjUu/wDu8mkVC3yrU0Uf8K96AHoC8n45qdRuP0pEXAwtPRdo96AHdTUg+Vaaq45NSrGu35x3oAWBTuz+FSLH5h7j3pyRZPzLxipVXaMKKAAfKij+6MfWlUFx6fWnKvPI+lO2n0oAB8q0BSfb607aqqNwpyjcePmoAaqEGnU6OHLNvBx2p3kx/wC1QBH1owfQ1MoVBhenvTjwue3SgCuVLDGDzxUNqSIGOD/rJD/4+1XnVlXpj0qG0wYW9PMkH/j7UANByKayEmpvJj/2vwpskJDrtB29+aAItje1IRkY6VIw29eKQjf1+agCHy29qSpSuDwKYyAg8c0AV5ISMtnv0qGSHzW+9tq50qKeHK5UHdnmgCmRkY9qYRirLKsozySOlQAcbW69xQBCw2n61HNHn5u4qd046euKZ0oApTqd2fwph+ZatTrtbPb+tVnTYf8AZoAgdSePQ1DNFvHuuatSDHPvUJGD+NAFKRd43fxLxUTrvFW5htnH90jJqswKn5vrQBXlO0g+vFQzx7SX6+tWXXI6fSo3GVb1xiswKG3EjH+8aY/3/wAKnmTKH/YqF1yPegCHv+NVJlPl/wC7zVtxiT2/rUdyMp+lAFENvX6gio5B/wCO5qd08s/7J6VE44b3zQBXnTPzenFVbn5Pm/CrzJv+U96p3EbSRYXk5oAhcc5/CoW+8amcZQ/nUcgwN350ANooByKKANCJP3gA6LyanYnI9zzUUP8ArPwqdD8/4UAPRcn/AHamiXLbuwqOMY59amRf3JH97mgCxAMfN+FTRcL+NNUbhj2qRRuP05oAcudq47mrCD5kXt0NRRDfJ/u4P1qzb87vl9MUATKvRakVcnFNjPB+tSLwn45oAkhTedx6L/OrMCndu/vdaihi2Kq9eatBfm2itABBuP0qZRtH4ZNNRf8Ax3FP2eYdvr3oAlhXYu7+I9PpViKLy+T9KbDHu59OMVMo3fnQA6NeM05BuP0oA3GpEXJVaAHJHv5P3anhj3klunQUxY94Ce3WrXQUAGacgwM0KNlSRjndQACPnmnZoQFmxjGe9SJEEHzfNn0oAbFFu5b8KkSJVb5e/FPjj3rxx2qWKPy49vB96AI/Jb2p3kKRyKkzQBu6UAR/Zk/u07y1Vcdqf5be1KqEGgCN1Egwar6dEr2zZH/LWX/0Y1XAuxfxFV9Nixbsc/elkP8A5EY0AOMChTgU0wMOnpzUxQgdqMgUAVZYP3nzc8cU1oAF+XjmrlQ/ZyB1H5UAVT8pwaaY+eKsEbk9OKhkQxkfxf0oAhKhj3pvQ1NJ9ym5zQBVki28r0xUM0e5cr97rVxht4qGZNpDf3u3pQBTYbk9wKjcZGamkjMbk9dxz9KbIOd1AEBXcKrTQnbj8qtMNv4mmzLuT/d5oAoumTg9qhdcg/7OcVYkHRv73b0qOQ8igCvIm9feqd2pUZ/i6Ve27GPuc1Dcf6z14oApsueahb7xqxInlkr+tROuePQ1MgK1yoxj+91qqRtbHvV6Zcxt/s1Unjywf+7xUgV2Xd+eaikXdH9OasSdvpioZOW/CgCnKGeH/aXJqBzwv0q3Mu5mH+elVSdzMvpxmgCJzh6gkTy29qsScA/XFQ3S74vxoApsm35T6VGy/eWp5xlt397tULjBz60ARAY/Diignk/WigDUtR+6/Opox8v41GiBBtHrU0a4I9uaAHrxtXv0qzbryvt1/KoI03SA/wB3mrduQY2+tAEqff8AwqWMcH61DH0Y/lU6gKwX1NAEsEf8Xc8VaC/u1XvjFQwIPMYdlwRVhRk0ASRJhV9utTRReYPao0OFqaH5UPbmrSAmt1DDd+AqxH92o0QIu0dM1Mic4pgKoJU+44qeBNsY9+ajjj3HHYdaswLllK/dHFAEka7Ivfqan6VGo3H271KqZ5OetACouB71Yjj2MB/E1RxJn5m6dqsQxZbc31FAEiR7BgVIkezmmr94VIq7j3xQA5FwOad5Rk29lz1oA3Nj8/pU4ULwOnagBFGCqgc9qmiiwcn8qEhUbW/iHXnpUgH1NAABzwPejYxpyrtGfanYJ7GgBqptXFOCnHSneUPf86cDgUANCcfNn8KPLX/apwVm5WjZJ/dFADTGv+1UNhEq25+9/rJOn++1WNjdwMVDYq32dj6Syg/9/GoAdsajbg9Kk3cU3aH5oAhaDcepoxg1KybemaYVD0ARNAGbNRMvY1YYbD7etNZBIB+lAFJ49h9qYVB/+tVplG4q3TNVyGQ/N07UARMvGO+KjZc5DVM4+bp2pjrz396AKjpgbT9KrlPKbae54q9Ku6M/3l6VWnQEbv4l4oArsuD+tRMuV2n0qdxnHftUbrkZ9qAKskeCVPTHHtVUjO5e44q9OMqvtkmqsqKrZH8XNAEDrke9RPH5lTOMNUb/ACv7Yz+NAFG4TO1u9QuMH61buo1UsOyjIqsBvT5qLAQstV5Uy23+9yKtScfhVedPnDegxWbAq1BIu5F9uTVmRdj8elQyLtBHtQBWmXB3f3jVaWPYf96rcq5T/dyR7VWnBbaR0HWgCvMMmo6lf71Qv8smPbNAFSUZjHtzULfOuR25q1PHtdlHTFVgm0bfbBoAZiijpRQBqL80mPbNSofn/CmR9/rUittX8cUATQp8hz/EKtRDbGv0qvF96Ie1Wl+8KAHxjcoHtU0S5l/D8qZGOc9ulTWg3Qr7nFAFiBMEt/eqZBj/AIFUap5ShffFTIh+X/Zpx3Ak8vzML+FWrddz4PpVeKPc27+6cVag4Qn3qwJEO58e2amjH8VRou0ds5qaMYKj3oAkhT5Dn+IVaiG2NfpUcKbn/wB2pl+8tADoY+P97mph95frTY1Oc+1SW43fN26CgCaOIPIV7Lg/WrA44qOCPaN396pU6/lQA5FwcZ61J91aRF2jmpbcYbd/D0oAdHH5ef7x4qdISrZP4ZpsCkP07d6mC5PH60ACjeTzTlGwdaVEOOMdKei4HOKABF4z1zTs4oRfOJHpUyR7FxQBGsW9c7lGakCKB2p2wkj5fanfZDn736UCuMGFoB4qdV2qPpTsUCbKuflqKxG2GTOPmllOPrIx/rV0rlPwqHTx/o//AG0k/wDQzQUN2L7VH5HLbT1PSrU0Pm4524qMxeWf73vQJMrA5FIybv8AZ+lWHj8xcVC0flfzoGRMBnBppTA61PioyNp+tAEMibx71XxuHNW5F5z2qG5Tcny+tAFQjY22mOMHPrViZdycfWoiMg/TFAFdhtP1qvMNsu3ru5q1ID/3z1qOSPzV2+tAFORdj/rULLj5fap7ld0eF9aiflD9KAITwSOvaqrAM7L/AHTgVck7fWoZxyPxoApsuQV96hl6fjU0nySY/vcio2XB+vNAFa4XJ3f3uMVVcYkarr8xH6VVlQ+WPVc5oAryrtVveoZBvTFWJKibiSoluBQuflXd+GKjkH8Xvip5E3koexzUDcp+FICFvvtVWU/JKP7vFXJOn41Xlj2vn+9zQBTkPyVDIuW3e2KsN95vqahdd3T1oAhnX5t3rxiqsn+sarU5ygPvVWZNr7v71AEJPJ+tFSYooA0o+fzqZRhl+oqJV2n8amQbnX65NAFmFMtn+70qxGM8+9Qwrtz79Kmi5/OgCRRhPwzVqGPawVfXNV1Qt8o9KtQHMn4UATAB5P1FTR1Gg43VIvRfpTjuBNH8sDe5yKtAfLj26VDEnKqfTmrEf36sCQcn8amt1O9j27VHH0P1qxAMov1/rQBPCmxAf73NSovtz2poGAo/u8VIv3xQA7O1Pwq1DHsYKvY5qGJBJJg+lWLcEkt6CgCbqeKfGuMcemaSMd6kUbUz7UAOUBpFU1Yij3kL2qKBOAzfeqzAu0bu/wDSgCTtTkXA6c01FyPpU0a96ABF2j+dSIm899vcim9amRfLTHryaABUVF9utSwxYQFs7qRIAyfN68Cps0EXDFFCqWP+zTlG31oENwfQ05YxjpTh8xp3lN6rQBXnmgsreS4uJre1treNpp555RFDBGgLPI7sQERVBZmJAUAkkAV5f+z5+2J8Nf2m5LiDwT4rsdXvLfzJ5LJkkt7pYwwUyCKRVYx5YYYAg5z7n5o/4OGfjVqnwu/YZ0rw/pM8lqfiH4nttH1CWMncbOKKe6dBj+9JDbg56rvHOTWN/wAEE/DugXP7Avxa8Y6hpKv4i8L+KbK4s9UMINxBDGqB40fGQjxyzIwzgiU55AIwlUcavKdMad6fOfoEBj1oxmpZY9jMpznJB9qY0eBx1963MHuV54vkJXduzTHTHyn5asYpssIkJb+LtQFyo8e0nH3fWo3XcP5VZdcZU1A6GM80FXIyM9ajI21NIvemMu4UAVWTY3t2qCUYfP8Ae6VcdfMT361Xmj+Xn+HkYoArSLjt9aiYbW44qdjlT9Kicd6AK8y+W3otVXTY7LVyePzUx71XnH8Xr1oArSLww/Komz5Z/vYqdxjmonG0/WgCnOgA3d14qF+gq1JHlyrdzmqpXcPxoAhYbWqvPyzjvj+lWJeNp9eKinXBVu7GgCk/Ib1X9Kif71SkZlk9zUcgwG+tTICvONrZ7YxmqjqVUr3xVu85h/Gq9zkPu9Tg1IFeTp9DzUM6749392rEgyWHrUMgxC4/CgCjP8s647jJqMjB/Wpp48vu9OKjkPK/7ooAruP3R+lVJPmiX2zmrrLtOKrzrtDj2/pQBXoozRQBrR9T9MVJbr87HscVHH0P1qaJdyL2yefzoAtAZhQeoxU0Y27R6VEo27fwFTIMt9KAJ7b/AF34VYtP9QKrw/dY989atRx+WMe9AEsR+79f61KgzOvsTTEHNSwD73riqiBat0+Vm96kh+431NRwJtjH51Mi5XjuKoCbG4496sxpmTaP4SDUEIzJ+FWLdcOx9aAJlG4/Spo+h+tRxjn64qRlyuFoAmiPyN35q3jmorRRvHA6elTKcsB+NAD0U4xUi9VX1pIxzmpIo/MOfTpQBNCMOq4zj/Cp8YWmQjCdOScipE+Yn0HFAEijcfpzUlNRcCnxpvcZ+7QBLHGBEvuKmhj2rn+9zxTI494PYdqmUYAA9MUEth0FPRdopFj28nn2p4Qk0EgBk1IowKRV2/40pBYHFABRinLbfL94+9ONv/tUAfmd/wAHL2lSt8Efg/qS3CLFa+KbuzMG47pZJbQOrgdCEEDgnOR5ox1OLv8AwRP1a88M/wDBKD9p7UJ/tL2vkS20TxHc1u8lm0QlbPCqvnq5IJIVGYcgCq//AAX9+Dfjv49+NPhPoXhKwuNYsNFtNR1a6sreI70mklt4kkLjOcojqoxxiT144f8A4JD/ALQeveDP2V/jx8D3+HmueIrj4j2Elv5tvqltDb6Q8tvPZySyljvZfMKp+6V8Nbypw6Mo8+rGbxHN0R6ELex5T9YrmLy7iVO6sVJz1qEjBrJ+HGm6vovw68P2uv6hDq+uWmmW0Oo30MRjjvblYkWWVVPKh3DNg8jd+A2iue1ehucMtyF13CmkYNTMnHApjpnrwfWgkikHyN9DzVeRPMGKtFNoweRUMsfl80DW5V6Go2Xafqankj6t+lR/eH+NBZC/3/wqCZdrbv71WHXCnI5xUbpuU/p7UAUnj8uQn+9zUb/f/Cp5l3A9tnWoWXK+9AELHa+PxqvKmzcvtViRf3mfbFQ3Ccq2ec4+tAFNBhMe2KjkGR9M1PLxIahf7rfjQBXmjw4f+7xiqrJsbH41dm5jqncYAVvbBoAgcbVI9qhmXcn+7k/WrD/e/CopBkMBQBSnGCv45qFz81TzLuB7bOtQPnOaAIiOfxqnN9xfrVxuJfwqq/8Aq29hWYFeToPrUPf8akzmNfrTJBgj9aAKlx91vr/Wq8nQfWrU6Zfb/e5FVyM+4oAgf7/4VXkP75qnm+6v1FQzN8+MfjQBRkGZW+tFK/8ArG+tFAGzH0P1qxbn5V+v9ahHLD61agTEpH93pQBN3/GpkOAfrUcfU05hti+oBoAsQ8I31q5nmobdA7YPpUiHMn/AaALCdamtwV3E9D0qGP7lWY+REvqK0WgE8f8Aq1+lTQ9vpUa/eX8qmT7n/Av6UAS2w3R7v4jxVuIFY1Ddaq2X+qX6/wBatyf6wf7woAkTov4VPGf3q1HH1NSxDEbN3U0AWbcYy3fOKljXnP4UxF2R/r9alVdv50APQ4SrCcRp9Kh27mX61agQEn2xQBInEa/SpEXan15pEGTn0qRD8/4UAPJ/OpYeEUVHEoM2farMHzSn/ZoJkSINsa/TmpIxnmmEZ/4FUqrjatBIKNxqTOKAMCnQRiQbz9MUAEUe/k9KkVBH+PXmnKuMD3qRIcfe5z0oAjKsfurQI5Cfu45qwP8A61ZfjfW5PDHg3WNTh2+bpthcXabhkbo4ncZ9vloAzfhbolr468aeINeuIY5re3b+zod5O0xWxO5iAehmaYg9cEc1Y/Zi+D8OhaBdfatRvb64s7cwBLiKNBDskXPEaqCzfOW6cj7oJJPRfC/wZa+C/gnY2kUjlp7aG1k3NuDowUS4H94RCQ8c8Ma0vAdtd+HfFkk11dJdWutXkgz9nSERieYrtzn5iGmiGeOjcdMTPXU7NjP8V2S2viS8RfuTYulGOAshbp7B1lQe0f41lyxY+7W/45KxTaarqyyb54VOPvr+7YD6Lhv++z61jfdbH4UR2Oep8RXB7d6a65GfapLlfL+f8KbVGZDJ0H1pjLuFSsfnNRsNp+tAFfGJce9V8Yq5Mo2578VVuflG78MUFxIpBk/hioj8pNTOPl/WonGDn1oGVpY8O3oxqueCfY4q5cDgH+7VSc7Zv97mgCCT+tQz8qPrVhhtP1GaidMAr7UAVJz8qn3NV3X/AMeq1LFsjZT/AAiq7Lhf90UAQldriqc6eYm33q6/3vwqCVMS59qAKbjK7veoW++amP8Aq/wqOToPrQBSl6TfWoGOVP1q5OgBHvmqbR/eHvQBFKP4u/Sq13wz/SrUowMe9QXCZO7+9wRWYFFFzF9ATTJOoqaRcOwH0qGReP8AdzQBXm/4+V+lVR0qzOcXC/Sq7p5bY/GgCtKMov1FR3HRfqamJ/d/hUUy7k/3cmgCs1srNnnn3oqSigDQX7y/UVag/wBfJ+FV4huk/WrFuD5jN696ALEfU1I43Rgf7IqNF4HvjNTxD94v5UAWbM5kH0qeP7hqK3GMnv0qaIfzoAkj5X8auQJkL/sVVQYK/UVct+rfhWgEiDLfSplH7v8ACo4+h+tSoCygAZ4oAtwD5/wqZB81Qwf6z8KnT7/4UASxjv61OFzCPoKhT7g+lWbf/ln9P6UATA5T8KsR9T/umoVXc34VNGOv5UASW3MrfhVqCPYM/wB7mq8CYG7u3WrQ/wBSv+7QBJH0P1qROEH0qOJeF9+tTBcjaooAfbDEeP4s1agH7umQoDJ+tTZxQS2Oj6mpI+/1qNF2ipBhV/Dn60EjhH5rbfxqwOBUcC4+boamgXc2ew6UAOgTjd61JRSou7qPpQAmfmxVXXNCj8TaHfaZM/lQ6nbS2bv/AHFkRkJ/AMavBdtBGaAMT9nDx4njP4BWbaks0eqWNi1rexwPsms7mJHhlVTg7HB8xCecMHXscd54I8IWMsdpM1tZxi12OrKnUpjaCepGQDgkjgHqMnw3x18O/EHg/wAbXHirwbG902ot5mp6Us6xSTS4wZoSxCEsAN8bEbm+dW3M4bsvBfxh8QNY/ZV8K6xb3kiBd935cNvB23O+8kgf3YwxPA460HVzJq50/wARtT/tv4gWsEcCw2+h2cvmMJhJ9omuGjI4H3QiQHryfOHYc0ZI96YqPTtPazt38yVri6mYyzzEY82Q4ycdhwAB2AAqbpQc83dlYjDbT2qBl8kgetW7mPK5UfN0/ConAkQ9+4+tBJXdc1HIP061KoIHzdaYRyaAIZV3oRVcqA20jpVkDBb68VFONr59sZoAqEZT8Kik+430qZk8tyv0qNxkn0NBoQtzAfcCqspDRn61cxiq0ibyw/vNQBWkGAPrUT/e/CpWHyjvzUM3G0++KAK84yWH+elVWPDD061cnTDBv71U8Zmf60ARyDnNV5zh/wAKsy8A/X+tVrw4i/GgCq8fl7l9qhk+430qxP8A69vwqCb7r/T+lAFaXon0/wAKrONrt9atyruiB/uiqc42zjH8XJoAilGfzqCc5RfrVg9arzDMa1mBVk/1jVA/3W/Gp5l+YN/eqBuQ340AQzD5PyqpN/rPwq3Mcxn61UuOHz2x1oAhlGSfpUMn3G+lTS9T9Khk/wBW30oAhooooA0of9Z+FXIf9WPxqnD/AKz8KuQ/6sfjQBKn3V/Cp4/9YtQJ91fwqeP/AFi0AWoPun61ND1/GoYPun61ND1/GgCdFLyKB65q1Cdu72/+vVSMb5P90g1ahOVf6VoBYThM+vNWLP76/wC7UEP3U+n9Ks23+u/CgCa3UkluwFWI1yfrxUNp/qFqeL+H6/1oAkUfOq/hVuBMFfQcVVX/AI+F+pq7B/q2+tAEiH5/wqWI5B+tQw/cb6mrGNx/GgCaDmNfc/1q0owFH93iq6ja+PerHf8AGgCRT84qxbf678Khj6H61LbZ3bvwoAngP7z8KmC7mHtzUdp/qBUqff8AwoMx6jcfpUhXzBt9abGMc+tSwpk7uymgB4+5z6VZVdoqKFPMl/A1NnIoAB8zYp44wPwoUbVp8Yxz60AHlnvxQqbT1p3SigBMUhTdTqKAIym0/wAqbIP4qkkXv6U2gCPPFQSL5cpWp+/41HP90fWgCrJ/rWqKU4Iqa4XlW9Sajf7h+lAEDn5/wqG8/wBV+NWJPu00jJoApzrzu/vcVDJ0H1qab7i/WoXGR9OaDQhYbT9agf5J1H97mrMnUVWuVzMp7YoArA1A43p/u81Zm/1n4VBI25SfagCC4OFT6mqZQpJk/wARq9J/q2+lVbjqv40AVZT976/1qveHMP41bf734VERk/jQBTnX5t3rxVWY8P8AT+lWpvuL9agdsnHpQBXb/j3b6CqVz/x8L9KvS/6qT/PeqVwv75T7UAMk6r/uiq7/AOqP0qeTqv8AuioH4ib6VDApyf6qP8ahYbT9amk/1Uf41HJ1FICrJ9x/96qt7/qfxq2U8zcvq1VLw/ufxoAif7/4VFIu8sPapnHOfwqFuWNAFeio5BmVvrRQBrQ/6z8KuQ/6sfjVOH/WfhVyH/Vj8aAJU+6v4VPFzIPaoE+6v4VPCW3/AOznmgC1D9xvrVhBtNV4fuN9asqNx+gzQtwJbb/Wv+FXAMQr7rVO2/1r/hVz/lgv+7WgEsP3U+n9Ks23+u/Cq0P3U+n9Ks23+u/CgCxaf6gVPF/D9f61Baf6gVPF/D9f60ASr/x8L9TV2D/Vt9apxpumB/uk1chGI/ryaAHw/cb6mrC/eX6ioUXan15qZfvL9RQBaiG6dvbGKnQZaoIP9fJ+FWI+poAkj6H61Nb8IfrUMfT8amh+431oAsWy7YsGpoxxmm96dH92gzJU+4PpU0H+rb61Cn3B9KliO2BvrQBNbLyzZ74qYfex+NNjTYv605P9d+FAElSKMLUajLfrUlABTlgJHXFOhTI3dweKkoAi+zn+9TGGxsVYpkqZX6cigCI81Gw2tUlNkXjNAEL8TfhmmyjMbfTNPkX5t34UyT/Vt9KAKpG6HnsDUfWpBxAfoaj7j60ARSD72PWmVI33m+pqPv8AjQBUkXdD7jmoc7lb/dNTuCsbZ9Krx/6r/gJoLRHJ1FRTD93Usi5H0qOb/Vn8KBlOb/WfhUMo2hvpU03+s/CoZv4vpQBDJ/q2+lVbjqv41ak/1bfSqtx1X8aAIH+/+FRd/wAalf7/AOFRd/xoApzfcX61DIMc+9TTfcX61DJ0H1oAgZdwb3qpKuEb2PH51c7/AI1VuPut9f60AV5Oo+mKryf6tvpViX7tQTDarfSpkBSk/wBVH+NRydRUkn+qj/Go5OoqQII/9Yf941Su/wDU/jV2P/WH/eNUrv8A1P40ARv9z/gX9Khb7xqZ/uf8C/pULfeNAFR/9Y31oof/AFjfWigDVh/1n4Vch/1Y/GqcP+s/CrkP+rH40ASp91fwq1B/q2+tVU+6v4Vag/1bfWgCeH7jfWrUfVv901Vh+431q1H1b/dNOO4Elt/rX/Crn/LBf92qdt/rX/Crn/LBf92rAlh+6n0/pVm2/wBd+FVofup9P6VZtzzj+LrQBYtP9Qv1qxGuCPbmq9p/qF+tWEO4r9aAJ7fktVq3/wBU31qpG+xm/wBqrcH+rb60ASI+5D7cVOv3l+oqKMhQPpUq/eX6igC1B/r5PwqxH1NV4P8AXyfhViPqaAJh0X/dFSQn9231qFhujH+6KsIwZOKALVOj5UfWm0+L+H6/1oMyUDAx6cVIf9QPoKj7/jUh/wCPcfQUAXB0p0fQ/WmjpQh/ffhQBKn3/wAKfTE+/wDhTycCgCaP/Vr9KkiTzHwfSo4jmNfoKltziX8KABocDcvAA5qJW3L06jGKmmbhRUdAFbPzsv8AdNJJ92lx+8Y+ppJPu0ARydB9aaRuFOk6D602gCu67XYYyOmKrbsOw/umrUpw7fnVUD94x/vGgBjfe+vNR9/xqQ/eb6mo26N+NAFabdht3pVaP/Vf8BNW7z78n0qpH/qv+AmgqIx/uH6VFN/qz+FSv9w/Sopv9WfwoKKc3+s/CoZv4vpU03+s/CoZv4vpQBDJ/q2+lVbjqv41ak/1bfSqtx1X8aAIH+/+FRd/xqV/v/hUXf8AGgCnN9xfrUMnQfWppvuL9ahk6D60AQ9/xqrcfdb6/wBatd/xqrcfdb6/1oArzfdqGfo3+7U033ahn6N/u1MgKMn+qj/Go5OoqST/AFUf41HJ1FSBBH/rD/vGqV3/AKn8aux/6w/7xqld/wCp/GgCN/uf8C/pULfeNTP9z/gX9Khb7xoAqP8A6xvrRQ/+sb60UAasP+s/CrkP+rH41Th/1n4Vch/1Y/GgCVPur+FWYXARhnvVZPur+FTINzigC3CMRtVlDgn6Gq8b70P5VOOtC3Amtv8AWv8AhVz/AJYL/u1Ttv8AWv8AhVz/AJYL/u1oBLD91Pp/SrNt/rvwqtD91Pp/SrNt/rvwoAsWn+oX61Yj/hx61XtP9QKni/h+v9aAJ4SA7fXircH+rb61SX/j4X6mrsH+rb60APibKN7HFWF+8v1FV4fuN9TVhfvL9RQBag/18n4VYj6mq8H+vk/CrEfU0ASRnI+nFSwDMZ+tRR9D9amg4Q/WgGXKfEcBfr/WoYH3pmpY/u0GZNnNSfeg49AKiT7g+lTQf6tvrQBaRty8Uqf6/wD4DUcH3T9akHD7vwoAkU4apPvCo6en3B9KAJbfCoV754FSdar5wakWddvPWgCTGKbK2EP0I+tJ56+tRyNvb2oAQcCmSH5sU+mP9/8ACgBknQfWo5P9W30p0jfPt9s02T/Vt9KAK4Y+Vu74NQ9/xqQf6g/Q1H3/ABoAjb7zfU1Ge/41JIdu761HQBXum3NIRzxVWP8A1X/ATVh/9UfpVeP/AFX/AAE0FRGP9w/Sopv9WfwqSQ9vWoZn+Xb3oKKs3+s/CoZv4vpU03+s/CoZv4vpQBDJ/q2+lVbjqv41ak/1bfSqtx1X8aAIH+/+FRd/xqV/v/hUXf8AGgCnN9xfrUMnQfWppvuL9ahk6D60AQk4z9aqznKN9f61YkGVYdj1qrI26NvrQBBL/TNRT9G/3amk5I/3RVeU5RvpUyApyf6qP8ajk6ipJP8AVR/jUcnUVIEEf+sP+8apXf8Aqfxq7H/rD/vGqV3/AKn8aAI3+5/wL+lQt941M/3P+Bf0qFvvGgCo/wDrG+tFD/6xvrRQBqw/6z8KuQ/6sfjVOH/WfhVyH/Vj8aAJU+6v4VPH/rFqBPur+FTx/wCsWgC1B91vrU0XH51DB90/Wpo/60AWLb/Wv+FWlfdFj+6tU0bDjHcjNWouQ30q0BZh+6n0/pVm2/134VVj+4vsKsWhzIv+7TAtWn+oFTxfw/X+tVrY4OO2OlWIzx70ATL/AMfC/U1dg/1bfWqEZzLHV2F8Hb6mgCWH7jfU1YBwfxqugwT9KsA5oAsI29g3vVjuPrVWA4Rfr/WrQOcUATR9D9amtv8AXfhVdeGqeBtsvPpQBZtP9QKlT7/4VBA+1tuePSplO1ufpQZk0bZGPSpoXwNv941Ahw1PDbDu9KALcL7ePxqWqoOVz0q0DmgCRW3ChDtP1pifep9AElFMD46/nTgwNAC0UE4ppkH+97UADtgfWm4xR1NNdsD3oAb3P1qO4+6PrUh6VDM2ZOPu9qAIbj7qfU1GTgfTmnSvuO3071HJQAyU5B+tRSyeUuffFPf71Q3n+q/GgCCf/Vj61Ex2j6jFSzt0HfPSoZOg+tBoRydRVa45uF+lWHOWqCQ7rlfbg0AVnfe2fwqGRtyk+1SjpULHEf14oAjk/wBW30qrcdVqxO+2Pp14FVHfewH904oAiY5b9Kj/AIvxp8pxu+v9ar3bFIuPWgCCb7i/WoHbJx6VLPxKV7DtUMpwGoAhl/1Un+e9VZ5APl/vc1Zc5gb6CqVz/wAfC/SgBknVf90VA5zE30qeQ4K/7oqCQ7YvwxUMCnJ/qo/xqOTqKllGI4/xqFzlqQECHDt/vGqd3/qfxq0/3H/3qq3gxD+NAEbnjHvmoW+8alf7/wCFROcM1AFR/wDWN9aKH5kbjqaKANWE/vPwqzbyZLL2Wqg+8v1FWoP9fJ+FAFiM/pU0Zw6k+mahj6mpJP8AVf8AARQBetj8h+tTQn+dQWv+tH0qWNv4fbNAFhT8y/UVct+rfhVGM4UfWrUbnK4/jrQC1H0P1qaJzGAw9O9Qx9D9akH+r/CgC5Bw/wCFTp9/8Kgjba/6VOnD0ASpxtb+6KtQHcyn/PSqsbZGPSrMLbFU+g/pQBaQ4b8KljPB+tQHlanj6t/umgCaE/KPXnNWgcQp9Kp23+tf8KuRSb1A/uigCVGyqnvTyN6frUcfQ/WpV5QfSgCyPvL9RVhxub6HNU4HLpu9+KtRHMYoJkSqdwFP27l+oBqOPqaehwcetBJZifevNSwNg7fxqpkryKsUAWAcGnK+TzUUUm4e/en4zQBJnNAODUR3D7pxThJgetADyxI7UU3zP9mmsWJ4OKAHs2BTCcmgCkdti5oAZPKY0yvrULDZG30705iWct+AqG53GTb2XmgCOM/IKaxyfpT2baKjf7rfjQAzduLfXFQ3B3/L261Kz+WN3pVZm2D8aAI5H3yk/SonOW+lOzhPwpjNgM340GhGep+tV2ba5PoamZsRs341VlOFIPLMc0ARA8VBN91fqKmk6D61E/3/AMKAIrj7q/U1RJxJJ7HNW53wW9BziqjD77f3qAI5Dlfxqvecw/jViRu1V5ySwXsBQBXn/wBe34VBN91/p/SpZZN7M3tUMpyp/wBrigCJv+PdvoKpXH+vX6VclJUKPaqjks7Z9aAImbJ+nFV5/uj61NN1/GoZ/uj61MgK9x91fqarscBvxqaU5c+lQP8Adb8akCGUYjb3OaqXPz/L261cm/1Z/Cqc3+s/CgCGU4J+lQy8o30qab+L6VDJ/q2+lAENFFFAGgv3l+tWoOZm/wBrpVNDuHNWLf7q/X+tAFyPqacT+6aowcH6nmpkG5T9aALUb+WQ3tU6/wCt/wCA1UiYshzVwDDZ/CgCaP7tWYusP0qtHxU0Dlj/ALnStALi/eFTIeMe/wClQIcqp74qWI5I+lAFi0YtGueef61ckOJB/vCqNudhx2HNXEbzUDH1zQBYj6mpoxuhb68VXRunvipoXw+3+8c0AXAcx57YqYHmq9v90r79KmRs9+aAJlO119yKtRNsfGPvVTA8xOasRMC0Zz9fagC4jYOKen3vwqIGnq/y5oAniO1vbpVi3yJGH5DNVc4/nU0bGQK3IoB7FrOPw61IrfdaoR8yL/tDmpIzgY/KgzJgcinRPh+SfzqJGweTxin0AWFOGz+eKmSUP7Y9e9UklZSF/hz1qYMrd/1oAs5zRVdZigwPmpftD/3R+dAE9HWoPtD/AN0fnR5zMMbdtAEryhP/AK3aoWbdn0z3pMgVHNJn5RzmgBLh/l2qcN149KaTk0gXDZpGcY6igAdsnFRO24052wpPeowflyfxoAZO+Pl/vVVueU2jrnNTN+8lz74quTub9KCojXOE/So5Gzx+dPdsnrx1qInLGgojnbau3+9xVW4H79fYVPLJuf8A3arH7ze5oAa/UfQVC7Zy3tUjNzz9KhkOIj9KAK8r+YrN6iq7t8v+8KklH7lR65zUTjG36UARv9/8Kgm/1n4VMDvc59cVVmm2jcfpQBXIxH+FRydB9akfhffp+FROct9KAIJJN7Y/u5qq52lvrUznaZW9DVeT7v40ARynj8ahnb+HuDk1JI3zbf8AZzUF5y8n0rMCvKf3jfnUDtwf9rNSId0Z/wB01HJ1FAFa4Y+co7Y6VBMf3n4VPOM3K/SquMsW7mgBkjbg30qGT/Vt9KfK21F9ziorkZRf9omgCMHIoqFrnYxXjjiigDUjPB+tTwttRf8Ae/rUEfVv901JbtlmX0oAvA5x9alQ4b61ApxEh9s1Mh3FTQBNA+Vb61cVw/SqlsP334VZtP8AUigCxC2anhON30qtGcBfrU0b/vF/2qqIF6Fsxr9KlQ7VB9qgtz8jD3qSPgMPqaoCzE+Jse3FWrd9zFey1UHDD61aibZK3+1gCgCxGf8Ax3FS7zGA3tmoVbafrUsfQ/WgC3C/ltuPpU6ja+fwqnB9xvrVqOTzF3D1oAsRnnFSRMFJz3qFH5zT1Pzq3agC/Cd0f+7x9adGMZHrzVeFiZFx908/pVhTtagCZG3CpIpMMFJ4qBW3H8al60AWoZNvyt24FTZwaqxvvjx/Eo5qa3bcjZOWz3oIZMriTjvTxIc9qiI4p6tuFAiWlRzH93HNRKdpp6vuoAlWfj5utL56+tRUUAS+evrSNcKBUdHWgAMrSJ26UdKCcCmM+4d6AFdtoph+VfpQx20xjuNAAWLVG8qlWXPWnPJsquTtZm7dRQAyWZkkVR3GaYowKCdzE0x23fnQaIjkbag/2uKax2qfYU5/vfhUM7ZIX+6eaAIZSAGz/wAtKhY7Vp8sm98D+HioX5b6cUANk6fjUFy+Av1qV/mk/DFV5n3MzD0oAhmOZPpULt1/2c07zMru9ajduP8AezQBG52Kx981TuRlFXPJ5qxO+HVfXmq83+s/CgCJ/v8A4VFIdu4+lSTfxfSoJW2p/vZAoArykANn/lpUDnIxU0/VfxqF+tJgQkZfP4VVlf8Adsx78D8qtd/xqnN9xfrUAQn92mPwqOTqKkdsnHoah7n60AV5n/ebj/DxVV229PWrFx91vr/Wq8nQfWgCGfhV/wB4VHcfdT6mpX+/+FVpmIkb+6OaAKj/AOsb60UrqS7H1OaKANaNgSfoRUsB2yN23YxUEf8AWplPzL9RQBcjbehH90YFTRHCr7darwtgt+GKsRng/WgCZJNh3D0q3bnaCuO2RVJf9X+lWonw/HrigC1GeKkXjafQVEvElSxn9KcdwLULDep6ZHNWE5b8Kpo2YD/s8VbVtv5VYE6cj8asQN8q/X+tVVbafqamtz+8b8KALwOcVIDtaq8Llhj+70qZG3CgCxbth+fu4zVi3O0FcdsiqfVB9KtJJtbI57c0AWozxUinMfHXFQq3cVIjdP8AaxQBYhfcg7HpVmF9y4/iH61QL+Wdw7dqtJIYzuHpQBZRh+vFSo2R71ADnp2qRH70AS5wc1MrBlyOPWoA2RS+c0SN09aALkUqlB2YfrUlVT8y1NFLvTJwD6UEtWJlcAcmlDZ6GmZoDYoJJAcH19qd5n+zUXmN7U4NkUAP8z/ZpC+Rwu33pN1NZ8DigBxPHU01pABxz7U0uSO1FABnPX/9VNd9gPqO1Nml8uPIwTnGKjkbzH3Hr7UADtk7jUEknmn2pZJckr2prHAoKj3Gu2B700naKCcnJqNm3H8aChrvsXJqvLJwzdM9Kkml3cdl5qvK+5sdloAY3AY9+tRO2B15qSRuMVE5+b8KAGSyeUtVZmwu3v3FTXPz/L+NVpX3ysfpQBG+Bge9RyHLD9afI23cahZsRlvbNAEUhVpc9FXiqzN/ePtUk7ZRueTzx9ahfoPrQBDKTgevf6VHcHhfqakkPP4VXmOHZvbj8qAKxOZWz0BqKRuG+vFSMPvH+9zUTnnFKWwEN222Lj1qtcNghR65NWLn5/l7daqvIXJb2qAI3OGaoZDiNm/KpJTlf97ioZm2Jt/vCgCtPJzt9eaikPT86dcf69fpUbHJ+nFAEbNlqr3Bzv8Ap/SpmOI/wqq74iX/AGsigCOiiigDSj6H61Ioyq47HNQjg/jU0Z4xQBZj5kjP97mrK/fFU4X3KPVRVpDlF+lAFhG7e+altW2AL6c5qCNsYJ9KmiP7z8KALmfMww9c1Mj9P9qoIOIxUqHIHtQgLUL4BX+8c1YhJaPb6HiqasEZWPpVq2Pzc9MZIrQCyjbvzqUcEexquhIf2x+tTI2R70AXIG4z/e6VOjYP1qlC+UH+yPyq0hyi/SgCwh/h981LbHau38agjbGCfSpMkdKALkDfJj0qZDkY9KqRN/EOOeashuh7H9aAJkYt1qaBy3y+nIqujc+3epA3dTQBbtWwu38alB2tmqqPuyy8fSpon3fL/F/OgCccgH8akVtwqFG29acGz0NAEqlkB575qWOYSP8AL9c1AHG3n8eKcBtPU0CauWllZW6077UuarpMqr827NOznvQTbWxaU7lB9aMVXD4H3j+dAdiPvNQFrFjFGMVXLMB95qN5/vH86ASuTSTLFjd3qNpt5+U8Uxmz/FnHvTHmVl+XdmgfKPZtvJqJ33dOmOaafmHJJpB8o9qBrQXGKjY7j9KGbJ60xmyeD9aBiyH+GopJliPPpSu20ZPNV3fADN39aAGyyCPKd8VCo2J9BmnM29yaa7dvzoAY33W/Go2bYuadI2elQXOTIB/DjkZoAhupSPm/AVE3CH6U+Yh2x/CO1Qu2e/y4oAbJ0H1qGdiCtSMdzetV2Y723HjPFAFeX55c/wB3io2O4/QYqRm6n3qGRucd+v4UARv/AKpvpVNyRAv+1kVanbCfjiqsn3/YdBQBGwwFqJ+Xpzt96o2bYN1RLcCCWXJ3fhVVv9X+FSXQJhHuc1FJy34UgGSdB9arzNlh/s1M+S9VZeBK3vwaAInYtI2fXFQu2386e5wtRycD8aAIZiVj2+p5qvcfdT6mrE7fw/xA9KqynMh9ulADaKjJOep60UAamefxqRD834VDG28c1LF/D9f60AWID8xq1Ccx/wC6cCqS/wDHwv1NWoD85+v9KALCn93+FTL/AKxW98VAn3/wqWPofrQBaQ7ZPl9cVajPJqnb/dX6/wBatdx9aAJgN68/Sp4mLIfaoE6VNB90/WtALgbP51Ih+b8Kr2n+oFTIPkoAsRvhsdmq1b4EfXoeKpL9wfSrEJ2hT7f0oAtI3btipUbI5qv1T8M1N3H1oAsQv/D6VYgl3fL/AHeBVMfeX6irC/69PxoAsKcNUqNg+2Kipw/1f4UATo2xvrwanDYb5W+771Xp1t/rX/CgC4rgheRluozS4+bdVcHbKv41PG+8ZoAlU7l/Cl3tnrTE+/8AhT6AHk570AUzFPT7g+lAC4oE7KMbTxRRQAv2lv7ppCd53dKKKADFGcUUyQZf8KAFdsDimO3HXtS4xTH+/wDhQAjfOOaTIUUtQync30zigBrtvk5PGarsxc89uKknbA29qjoARmwKidsfXNPf7/4VE33zQA122ozd+o96rTtlTz8zVLK25vpnFVbn/j4X6UANdsDio24Q/SpJOq/7oqJ/v/hQBHMxRRj+LINVJyCR7dasTt+9UfWqY/17/wC9QAjnJxUTcsT36VIfvN9TUMjbfzxQBDdkEtzwBxzVVT8nPoTU033F+tQydKAI5Ov161BPJj5fXmp5OoqvN/x8r9KzArzHL/QVDK2D+FSCq833F+ooAbI2FbnnFVZ32rt/vcVYuPup9TVWVst9MigCOQ84qGVstjtjNSv9/wDCou5+tAENycTNVUvvO71qaVs+Z9P6VXj/ANV/wE0AN7/jRRRQB//Z";

        $user->profile_pic = \Upload::storeMediaFromBase64($profile_pic, 'user_profile', "/{$user->id}")[0];
        $user->cover_pic = \Upload::storeMediaFromBase64($cover_pic, 'user_cover', "/{$user->id}")[0];

        $user->save();
        UserVerificationDetail::create([
            "user_id" => $user->id,
            "email" => $user->uuid . "@mail.com",
            "education" => "SSC",
            "board" => "Dhaka",
            "roll" => "11111",
            "reg_num" => "11111",
            "group" => "Dhaka",
            "year" => date('Y'),
        ]);

        UserVerification::create([
            "user_id" => $user->id,
            "payment_method" => "Direct Payment",
            "transaction_id" => "created-by-admin",
        ]);


        return back()->with(["success" => "User has been created successfully"]);
    }

    public function changeReferredBy(User $user, Request $request)
    {
        $request->validate([
            'referred_by' => 'required'
        ]);
        $updated = $user->update([
            "referred_by" => $request->referred_by
        ]);

        if($updated) return back()->with(["success" => "Referred By User has been change"]);
    }
}
